services:
  mongodb:
    image: mongo:7
    container_name: yustream-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yustream
      - MONGO_INITDB_ROOT_PASSWORD=yustream123
      - MONGO_INITDB_DATABASE=yustream
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - streaming-network

  yustream-auth:
    build: ./auth-server
    container_name: yustream-auth
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=yustream-jwt-secret-change-in-production-2024
      - CORS_ORIGIN=*
      - STREAM_CHECK_URL=http://host.docker.internal:8080/live/live/abr.m3u8
      - MONGODB_URI=mongodb://yustream:yustream123@mongodb:27017/yustream?authSource=admin
      - WEBHOOK_SECRET=yustream-webhook-secret-2024
      # Configurações do OvenMediaEngine API
      - OME_HOSTNAME=host.docker.internal
      # - OME_HOSTNAME=ovenmediaengine
      - OME_API_PORT=8081
      - OME_VHOST=default
      - OME_APP=live
      - OME_STREAM=live
      - OME_ACCESS_TOKEN=maketears
    volumes:
      - ./auth-server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - streaming-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/conf.d/ssl.conf.production:/etc/nginx/conf.d/ssl.conf
      - ./yustream-react/dist:/usr/share/nginx/html
      - /ssl/letsencrypt:/etc/letsencrypt
      - ./ssl/certbot/www:/var/www/certbot
    depends_on:
      - yustream-auth
    networks:
      - streaming-network
  redis:
    image: "redis:5.0.7-alpine"
    container_name: yustream-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

networks:
  streaming-network:
    driver: bridge

volumes:
  mongodb_data:
  ome_mux_data:
  redis_data: